# Generated by Django 5.0.1 on 2024-01-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
                ('iin', models.IntegerField(verbose_name='ИИН')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Область',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('registration', 'Прописка'), ('extract', 'Выписка')], max_length=30, verbose_name='состояние')),
                ('state_date', models.DateField(verbose_name='дата прописки/выписки')),
                ('district', models.CharField(blank=True, max_length=150, null=True, verbose_name='район')),
                ('punkt', models.CharField(max_length=150, verbose_name='населеный пункт')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asb.country', verbose_name='страна')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asb.person', verbose_name='физическое лицо')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asb.region', verbose_name='область')),
            ],
            options={
                'verbose_name': 'адрес прописки/выписки',
                'verbose_name_plural': 'адреса прописк/выписки',
            },
        ),
    ]
