# Generated by Django 5.0.1 on 2024-01-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.BigIntegerField(verbose_name='ИИН'),
        ),
    ]
